spring.application.name=inventario

# puerto de la aplicacion 
server.port=8080

# configuracion de la base de datos
# spring.datasource.url=jdbc:h2:mem:inventariodb
# spring.datasource.username=sa
# spring.datasource.password=
# spring.datasource.driver-class-name=org.h2.Driver

spring.datasource.url=jdbc:${DATABASE_URL}
# La URL de DATABASE_URL ya incluye usuario y contraseña
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


#JPA
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true


# Consola H2 para verificar 
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console 